### ISSUE TITLE
aesthetic assessment is sensitive to the size of the input image

### ISSUE THREAD

**Issue by Nastu-Ho** [Q-Future/Q-Align#10]
![image](https://github.com/Q-Future/Q-Align/assets/39642013/c9ee3130-91f9-4024-956a-0d3f53969ede)

**Comment by teowu** [comment]
Hi Natsu. This is due to the pre-processing mechanism of the model, that images with long edge <448 will be padded to 448, which affects their aesthetic quality.

Please try with larger inputs (which will be first padded to square and then resized to 448*448).
