### ISSUE TITLE
prediction score

### ISSUE THREAD

**Issue by Nastu-Ho** [Q-Future/Q-Align#11]
![image](https://github.com/Q-Future/Q-Align/assets/39642013/3248f9f6-7570-4357-8691-37f159ac5ac6)

https://github.com/Q-Future/Q-Align/blob/3e134a1df0610fc8c9e5f5ff7b37ac0c818386cf/q_align/evaluate/scorer.py#L70

Seems to be inconsistent with the report

**Comment by teowu** [comment]
The two forms are equivalent (y = 4x + 1), and does not affect any correlation metric. If you use the hf.Automodel from https://huggingface.co/q-future/one-align, the one will exactly follow the report (range [1,5]). 

Refer here: https://huggingface.co/q-future/one-align/blob/main/modeling_mplug_owl2.py#L277

**Comment by theicfire** [comment]
This confused me as well, I didn't expect the two ways of calling the code would result in different scores. But I now understand they're just scaled differently!

**Comment by dongdk** [comment]
hi @teowu i try what u said, but get `score: tensor([1.8506], device='cuda:0', dtype=torch.float16)`, which ls less than the value `1.911` in https://huggingface.co/q-future/one-align.
