### ISSUE TITLE
How to train without huggingface_hub and offline?

### ISSUE THREAD

**Issue by RollingWang** [Q-Future/Q-Align#13]
Thanks for your interesting job, and I want to reproduce it in my server offline, but it's confused about how to avoid using  huggingface_hub?

**Comment by teowu** [comment]
If you are in Mainland China, please try to use hf-mirror.com;
You can also pre-download the pre-trained weights and save locally, and change here to your local dir:
LOAD='MAGAer13/mplug-owl2-llama2-7b'
