### ISSUE TITLE
output decoding

### ISSUE THREAD

**Issue by Nastu-Ho** [Q-Future/Q-Align#14]
I'm just getting started with MLLM and I want to see the full text output of the model and not just some ratings. I'm getting some weird output, so I'm not sure if the decoding code I'm using is correct.
![image](https://github.com/Q-Future/Q-Align/assets/39642013/f20b54f3-58e4-4da2-8faa-6b2731f2d50c)

The output is as shown in the screenshot below：
It seems that only what is in the box is reasonable.
![image](https://github.com/Q-Future/Q-Align/assets/39642013/e4057c8e-03ff-4600-a480-76f31c01f0aa)

**Comment by teowu** [comment]
Hi Natsu,

You have decoded the positions which should be VISUAL TOKENS into text. They are interesting, but not designed to be meaningful.
