### ISSUE TITLE
about the GPU usage

### ISSUE THREAD

**Issue by Gary-bk** [Q-Future/Q-Align#16]
hello, thank u for your sharing this work. However, there is still a problem can not be solved. The model's training is fixed to multi-GPU. If i want to train it on one or two GPU, how can i accomplish it?  Could you give me some possible instructions?

**Comment by teowu** [comment]
Hi, Gary,

Sadly, the one GPU memory at present is not enough to train Q-Align.

Best
Haoning

**Comment by Gary-bk** [comment]
Thanks for your reply.

**Comment by Eddudos** [comment]
Do anybody know how much GPU memory is needed for inference?

**Comment by dongdk** [comment]
hi @Gary-bk 
have u solved the problem of one-gpu to train q-align?
