### ISSUE TITLE
About Training with LoRA

### ISSUE THREAD

**Issue by Gary-bk** [Q-Future/Q-Align#18]
Thanks for your sharing. But I still have one problem can not be solved. When training a q-align model with LoRA and using checkpoints, the folders of checkpoints will be saved to the folder of trained model. When I try to load parameters in the checkpoint folder, it warns me that it does not appear to have a file named 'config.json'. So, I copy one 'config.json' from another folder to make it works. But is still shows me HFValidationError. Could you give me some suggestions about how to load these parameters (LoRA and checkpoint)?

**Comment by teowu** [comment]
Hi, for the lora model, you need to load both the lora weights and the base weights (where really contains the config.json). Please refer to https://github.com/Q-Future/Q-Align/blob/main/q_align/evaluate/iqa_eval_lora_split.py for more detailed reference.
