### ISSUE TITLE
ddp is too slow

### ISSUE THREAD

**Issue by lliee1** [Q-Future/Q-Align#19]
Hi, I appreciate your study. I'm currently trying to use your model for study purpose, and because of my gpu capacity, I use ddp for multi-node (specifically 2-node, 4 * A6000 gpu for each node).

When I use your "iqa_mix.sh" (Training kadid, koniq, spaq dataset, with per_device_train_batch_size=16, epoch=3, default setting of your repo, you already know), it takes about 85 hours for 3 epoch. Is it general? or Does my ddp code have some kind of issue?

I hope you have a nice day!

**Comment by teowu** [comment]
Hi, 

Please consider using Deepspeed with multi-nodes:

https://nlp.stanford.edu/mistral/tutorials/deepspeed.html.

Best
Haoning
