### ISSUE TITLE
_prepare_4d_causal_attention_mask_for_sdpa does not exist

### ISSUE THREAD

**Issue by theicfire** [Q-Future/Q-Align#20]
I'm getting this error: `'_prepare_4d_causal_attention_mask_for_sdpa' is not defined`

Which makes sense -- it's being used but it's not in the code. I'm currently a bit confused why I'm having this issue at all -- I'm just trying to run inference on the model.

Thanks!

**Comment by rokopi-byte** [comment]
Hi, inference code is working for me in colab. Be careful about transformer version (transformers==4.36.1 required)

**Comment by teowu** [comment]
Yes, please follow the correct transformer version. There are some library functions used from the transformers.

Best
Haoning

**Comment by kwea123** [comment]
it's not related to the version, I use `4.36.1` and still have the same error. I solved it by adding `from transformers.modeling_attn_mask_utils import _prepare_4d_causal_attention_mask_for_sdpa`
