### ISSUE TITLE
dataset for AIGCQA-30K-Image

### ISSUE THREAD

**Issue by cyy-1234** [Q-Future/Q-Align#25]
![image](https://github.com/Q-Future/Q-Align/assets/59501159/e824365f-1e99-4ab4-8161-2b93689a68bc)
![image](https://github.com/Q-Future/Q-Align/assets/59501159/6e9ca9a1-f4ec-4632-9a37-ed9aef0e489d)
作者你好，这个img的url前缀是啥，可以分享一下吗，谢谢

**Comment by zzc-1998** [comment]
你好，请你在此处下载对应的AIGCQA-30K数据集 https://www.modelscope.cn/datasets/lcysyzxdxc/AIGCQA-30K-Image/files
这个数据集中的图片即为对应的json里的格式，前缀无url

**Comment by dongdk** [comment]
hi @zzc-1998 but it looks like that the json file does not have the `gt_score` field. how to solve it.
