### ISSUE TITLE
Program hangs when training from the start

### ISSUE THREAD

**Issue by Teddy-Xiong** [Q-Future/Q-Align#7]
Hi, thanks for sharing this amazing work. However, when I try to do full training from the start, the program hangs after outputting the following:

<img width="973" alt="Screenshot 2024-02-04 at 11 11 58 PM" src="https://github.com/Q-Future/Q-Align/assets/35674445/e086d769-d4d1-44ef-a577-4f9258e0f74d">

Could you suggest any possible solution?

**Comment by teowu** [comment]
Hi Teddy,

This seems strange (the warnings up there are natural and not reasons of the error). Can you set some breakpoints (or line-by-line prints) to see where does this hang come from in the code?

Best
Haoning

**Comment by Teddy-Xiong** [comment]
Hi Haoning,

Thanks for your fast reply. Following your suggestion, I found the program stuck when loading the mPLUG-Owl2 model:
<img width="474" alt="Screenshot 2024-02-04 at 11 46 59 PM" src="https://github.com/Q-Future/Q-Align/assets/35674445/0c7059ca-f034-4614-9c68-4c454e8e11df">

Regards,
Teddy

**Comment by teowu** [comment]
Hi Teddy,

Have you installed the `flash_attn`?
Or, maybe you can try to modify the attn_implementation to "eager" here and see how it works.

Best
Haoning

**Comment by Teddy-Xiong** [comment]
Hi Haoning,

Yes I have installed it following your instructions:
`pip install flash_attn --no-build-isolation`

Unfortunately, the program still hangs after I change it to "eager".

Regards,
Teddy

**Comment by teowu** [comment]
Hi Teddy,

Sorry about the late reply. Training with a single 40G GPU is not achievable right now.

And for the hang, this looks like a deepspeed issue. Can you provide me with your environment versions?

Best
Haoning

**Comment by Teddy-Xiong** [comment]
Hi Haoning,

Sorry for the late reply. Here's the full pip list of my environment. I simply created the environment following the instructions you provided:

<img width="310" alt="Screenshot 2024-02-28 at 10 10 57 AM" src="https://github.com/Q-Future/Q-Align/assets/35674445/73c0b210-a175-481b-9327-8ab6b130eb45">
<img width="319" alt="Screenshot 2024-02-28 at 10 13 33 AM" src="https://github.com/Q-Future/Q-Align/assets/35674445/6d12c794-8e08-4cf1-8788-312c3ec089dc">
<img width="335" alt="Screenshot 2024-02-28 at 10 13 56 AM" src="https://github.com/Q-Future/Q-Align/assets/35674445/64014124-57a6-4115-afeb-a0bc7a3c17bb">

Regards,
Teddy

**Comment by teowu** [comment]
This seems okay. 

Recently I notice that this error might come from the kernel version that I have noticed this warning 
`Detected kernel version 5.4.143, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.`
on some of my devices.

**Comment by Teddy-Xiong** [comment]
Hi Haoning,

The program magically works after I pull the latest version. Maybe it's some random version conflicts. Thanks for your help.

Regards,
Teddy
